version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 286021655333.dkr.ecr.ap-southeast-2.amazonaws.com
  build:
    commands:
      - docker build -t awsbatchtesting .
      - docker tag awsbatchtesting:latest 286021655333.dkr.ecr.ap-southeast-2.amazonaws.com/awsbatchtesting:latest
  post_build:
    commands:
      - docker push 286021655333.dkr.ecr.ap-southeast-2.amazonaws.com/awsbatchtesting:latest


