version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - cd App
      - docker build -t $ECR_REPO_NAME:latest .
      - docker tag $ECR_REPO_NAME:latest $REPOSITORY_URI/$ECR_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/$ECR_REPO_NAME:latest
      - docker push $REPOSITORY_URI/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "submiting aws batch job..."
      - aws batch submit-job --job-name demo --job-queue test-jq  --job-definition test-jd