version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - cd App
      - docker build -t $ECR_REPO_NAME .
      - docker tag $ECR_REPO_NAME:latest $REPOSITORY_URI/$ECR_REPO_NAME:latest
  post_build:
    commands:
      - docker push $REPOSITORY_URI/$ECR_REPO_NAME:latest
      - echo "submit job"
      - aws batch submit-job --job-name demo --job-queue test-jq  --job-definition test-jd